version: "3.8"

services:

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/elements1/mosquitto/data:/mosquitto/data
      - /mnt/elements1/mosquitto/log:/mosquitto/log
