version: "2.4"

services:

  mosquitto:
    image: eclipse-mosquitto:1.6.10
    ports:
      - "1883:1883"
    user: "1000:995"
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/elements1/mosquitto/data:/mosquitto/data
      - /mnt/elements1/mosquitto/log:/mosquitto/log

  nodered:
    image: darignac/node-red:1.1.3
    ports:
      - "1880:1880"
    container_name: nodered
    restart: always
    group_add:
      - 20
    volumes:
      - /mnt/elements1/nodered:/data

  influxdb:
    image: influxdb:1.8.1
    ports:
      - "8086:8086"
    user: "1000:995"
    container_name: influxdb
    restart: always
    volumes:
      - /mnt/elements1/influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=db0
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password

  grafana:
    image: grafana/grafana:7.1.3
    ports:
      - "3000:3000"
    user: "1000:995"
    container_name: grafana
    depends_on:
      - influxdb
    restart: always
    volumes:
      - /mnt/elements1/grafana:/var/lib/grafana
