version: "3.8"

services:

  mosquitto:
    image: eclipse-mosquitto:1.6.10
    ports:
      - "1883:1883"
    user: "1000:995"
    container_name: mosquitto
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mnt/elements1/mosquitto/data:/mosquitto/data
      - /mnt/elements1/mosquitto/log:/mosquitto/log

  nodered:
    image: nodered/node-red:1.1.3
    ports:
      - "1880:1880"
    container_name: nodered
    restart: always
    volumes:
      - /mnt/elements1/nodered:/data

  influxdb:
    image: influxdb:1.8.1
    ports:
      - "8086:8086"
    user: "1000:995"
    restart: always
    volumes:
      - /mnt/elements1/influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=db0
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password
