version: "2.4"

services:

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    user: "1000:995"
    container_name: mosquitto
    depends_on:
      - nodered
    restart: always
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  nodered:
    image: darignac/node-red:1.2.9
    ports:
      - "1880:1880"
    container_name: nodered
    depends_on:
      - influxdb
    restart: always
    group_add:
      - 20
    volumes:
      - /mnt/pi1/nodered:/data
    devices: 
      - /dev/ttyUSB0:/dev/ttyUSB0

  influxdb:
    image: influxdb:1.8.1
    ports:
      - "8086:8086"
    user: "1000:995"
    container_name: influxdb
    restart: always
    volumes:
      - /mnt/pi1/influxdb:/var/lib/influxdb
    environment: 
      - INFLUXDB_DB=db0
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=password

  grafana:
    image: grafana/grafana:7.4.3
    ports:
      - "3000:3000"
    user: "1000:995"
    container_name: grafana
    depends_on:
      - influxdb
      - nodered
    restart: always
    volumes:
      - /mnt/pi1/grafana:/var/lib/grafana
    environment:
      - GF_AUTH_PROXY_AUTO_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
  
  caddy:
    image: caddy:2.3.0-alpine
    ports:
      - 8080:8080
      - 8081:8081
    container_name: caddy
    depends_on:
      - grafana
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dashboard:/usr/share/caddy
