@startuml
skinparam shadowing false

skinparam package {
  BackgroundColor white
  BorderColor black
  FontStyle italic bold

  BackgroundColor<<Environment>> PaleGreen
  BackgroundColor<<RaspberryPi>> LightSalmon
  BackgroundColor<<Hardware>> SeaShell
  BackgroundColor<<Docker>> LightSkyBlue
}

skinparam class {
  BackgroundColor none
  BorderColor Black
}

hide members
hide circle
hide stereotype

package "Environment" as E1 <<Environment>> {
  class "La Crosse Sensor(s)" as sensorLacrosse
}

package "Environment" as E2 <<Environment>> {
  class "MiFlora Sensor(s)" as sensorMiflora
}

package RaspberryPi <<RaspberryPi>> {
  package "Attached Hardware" <<Hardware>> {
    class "JeeLink" as jeelink
  }

  package Docker <<Docker>> {
    class nodered
    class grafana
    class influxdb
    class mosquitto

    mosquitto -down-> nodered: push data
    nodered -down-> influxdb: store timeseries data
    grafana -up-> influxdb: get timeseries data
  }

  package "Crontab Scripts" {
    class "raspi-health.py" as scriptRaspiHealth
    class "miflora/gather.py" as scriptMiflora

    scriptRaspiHealth -right[hidden]-> scriptMiflora
  }

  scriptRaspiHealth -down-> mosquitto: send RPi health data
}

package "External" as Ex {
  class "DiscordBot" as discord
}

sensorLacrosse -left-> jeelink: send data
nodered -left-> jeelink: receive data
scriptMiflora -right-> sensorMiflora: poll data
scriptMiflora -down-> mosquitto: send miflora data
nodered -down--> discord: send notifications
@enduml
